version: '3'
services:
  english-note:
    build: ./english-note/
    image: english-note
    container_name: english-note
    ports:
      - 8080:80
  english-note-server:
    build: ./english-note-server/
    image: english-note-server
    container_name: english-note-server
    ports:
      - 1323:1323
    volumes:
      - ./saveFiles:/go/src/app/saveFiles
