version: '3'
services:
  english-note:
    build: ./english-note/Dockerfile
    image: english-note
    container_name: english-note
    ports:
      - 8080:80
  english-note-server:
    build: ./english-note-server/Dockerfile
    image: english-note-server
    container_name: english-note-server
    ports:
      - 80:1323
    volumes:
      - ./saveFiles/saveFile.json:/go/src/app/saveFile.json
      - ./saveFiles/recordSaveFile.json:/go/src/app/saveFile.json
